version: '3.4'

services:
  ecommerce-db:
    image: mongo:4.4
    container_name: ecommerce_db
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
  ecommerce-api:
    image: ecommerce-api
    container_name: ecommerce_api
    build:
      target: ${STAGE}
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:3000
    environment:
      PORT: ${PORT}
      STAGE: ${STAGE}
      VERSION: ${VERSION}
      SEED: ${SEED}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}